server:
  servlet:
    context-path: /rag-chat
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:file:.env

  application:
    name: assignment
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ragchat?currentSchema=rag
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        default_schema: rag
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      continue-on-error: true
      mode: always
security:
  api-key: ${API_KEY}

