server:
  servlet:
    context-path: /rag-chat
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:file:.env

  application:
    name: assignment
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ragchat?currentSchema=rag
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        default_schema: rag
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      continue-on-error: true
      mode: always
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
    info:
      show-details: always
security:
  api-key: ${API_KEY}

info:
  app:
    name: RAG-Assignment
    description: Service to handle storing and retrieving chat history
    version: 1.0
    environment: Production
    support:
      email: ahmed.sayed.elhossary@gmail.com